
///////////////////////////////////////////////////////////////
// AUTOGENERATED DrawableScriptable Interface
///////////////////////////////////////////////////////////////

import JavaScriptCore

/** An example demonstrating the ability to parse json into a swift protocol */
@objc public protocol DrawableScriptable: JSExport {

    // Instance Properties
    
    /** The position of this drawable */
    var position: ModularVector2 { get set }
    
    /** The size of this drawable */
    var size: ModularVector2 { get set }
    
    /** The fill color of this drawable */
    var fillColor: ModularColor { get set }
    

    // Class Functions
    
    /**
    Creates a new drawable
        - Parameter position: The position of the drawable
    - Parameter size: The size of the drawable
    - Parameter color: The fill color of the drawable
    - Returns: (Drawable) A new drawable*/
    static func makeDrawable(_ position: ModularVector2, _ size: ModularVector2, _ color: ModularColor) -> Drawable
    

}