
///////////////////////////////////////////////////////////////
// AUTOGENERATED ModularColorScriptable Interface
///////////////////////////////////////////////////////////////

import JavaScriptCore

/** A color backed by r, g, b, a values in the 0..1 range */
@objc public protocol ModularColorScriptable: JSExport {

    // Instance Properties
    
    /** The red component of the color, between 0..1 */
    var r: Float { get set }
    
    /** The green component of the color, between 0..1 */
    var g: Float { get set }
    
    /** The blue component of the color, between 0..1 */
    var b: Float { get set }
    
    /** The alpha component of the color, between 0..1 */
    var a: Float { get set }
    

    // Class Functions
    
    /**
    Creates a new color
        - Parameter r: The red component, between 0..1
    - Parameter g: The green component, between 0..1
    - Parameter b: The blue component, between 0..1
    - Parameter a: The alpha component, between 0..1
    - Returns: (ModularColor) A new color*/
    static func makeColor(_ r: Float, _ g: Float, _ b: Float, _ a: Float) -> ModularColor
    

}