
///////////////////////////////////////////////////////////////
// AUTOGENERATED ScreenScriptable Interface
///////////////////////////////////////////////////////////////

import JavaScriptCore

/** A class that provides functionality for rendering things to the screen */
@objc public protocol ScreenScriptable: JSExport {

    // Instance Functions
    
    /**
    Adds a drawable to the screen
    - Parameter drawable: The drawable to add
    */
    func addDrawable(_ drawable: Drawable)
    

}