//
//  MustacheSwift.swift
//  Scripter
//
//  Created by Adam Eisfeld on 2021-01-17.
//

import Foundation

public struct MustacheSwift {
    
    public static let header =
"""
///////////////////////////////////////////////////////////////
// AUTOGENERATED {{className}} Interface
///////////////////////////////////////////////////////////////

import JavaScriptCore
"""
    
    public static let classStart =
"""

{{#classDocumentation}}/** {{classDocumentation}} */{{/classDocumentation}}{{^classDocumentation}}// No documentation specified{{/classDocumentation}}
@objc public protocol {{className}}: JSExport {
"""
    
    public static let classProperties =
"""

    // Class Properties
    {{#classProperties}}
    {{#propertyDocumentation}}/** {{{propertyDocumentation}}} */{{/propertyDocumentation}}
    static var {{propertyName}}: {{propertyType}} {{#propertyWritable}}{ get set }{{/propertyWritable}}{{^propertyWritable}}{ get }{{/propertyWritable}}
    {{/classProperties}}
"""
    
    public static let instanceProperties =
"""

    // Instance Properties
    {{#instanceProperties}}
    {{#propertyDocumentation}}/** {{{propertyDocumentation}}} */{{/propertyDocumentation}}
    var {{propertyName}}: {{propertyType}} {{#propertyWritable}}{ get set }{{/propertyWritable}}{{^propertyWritable}}{ get }{{/propertyWritable}}
    {{/instanceProperties}}
"""
    
    public static let classFunctions =
"""

    // Class Functions
    {{#classFunctions}}
    /**
    {{{functionDocumentation}}}
    {{# each(functionArguments) }}    - Parameter {{argumentName}}: {{{argumentDocumentation}}}{{^ @last }}{{tags.newline}}{{/}}{{/}}
    {{#functionReturnValue}}- Returns: ({{valueType}}) {{#valueDocumentation}}{{{valueDocumentation}}}{{/valueDocumentation}}{{/functionReturnValue}}*/
    static func {{functionName}}({{# each(functionArguments) }}_ {{argumentName}}: {{argumentType}}{{^ @last }}, {{/}}{{/}}){{#functionReturnValue}} -> {{valueType}}{{/functionReturnValue}}
    {{/classFunctions}}
"""
    
    public static let instanceFunctions =
"""

    // Instance Functions
    {{#instanceFunctions}}
    /**
    {{{functionDocumentation}}}
{{# each(functionArguments) }}    - Parameter {{argumentName}}: {{{argumentDocumentation}}}{{^ @last }}{{tags.newline}}{{/}}{{/}}
    {{#functionReturnValue}}- Returns: ({{valueType}}) {{#valueDocumentation}}{{{valueDocumentation}}}{{/valueDocumentation}}{{/functionReturnValue}}*/
    func {{functionName}}({{# each(functionArguments) }}_ {{argumentName}}: {{argumentType}}{{^ @last }}, {{/}}{{/}}){{#functionReturnValue}} -> {{valueType}}{{/functionReturnValue}}
    {{/instanceFunctions}}
"""
    
    public static let classEnd =
"""

}
"""
    
}
